/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmapTransformer;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws IllegalArgumentException {

        if (args.length != 3) {
            throw new IllegalArgumentException("This application requires exactly 3 arguments: input file, output file, and transform operation.");
        }
        String input = args[0];
        String output = args[1];
        String transform = args[2];

            Bitmap bitmap = new Bitmap(input, output, transform);

            bitmap.readFile();

            switch(transform) {
                case "horizontal-flip":
                    bitmap.horizontalFlip();
                    break;

                case "vertical-flip":
                    bitmap.verticalFlip();
                    break;

                default:
                    System.out.println("Operation " + transform + " not supported. Available options are horizontal-flip and vertical-flip");
            }

            bitmap.savefile();

    }

}
